# Generated by Django 5.0.1 on 2024-01-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='shoe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
    ]
