# Generated by Django 5.0.1 on 2024-01-12 13:10

import django.db.models.deletion
import shoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shoesize',
            name='shoe',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brnads/'),
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shoes.models.ShoeColor.get_images_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=shoes.models.ShoeColor.get_images_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=shoes.models.ShoeColor.get_images_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=shoes.models.ShoeColor.get_images_path)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
            ],
        ),
        migrations.AddField(
            model_name='shoesize',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoecolor'),
        ),
    ]
