# Generated by Django 5.0.1 on 2024-01-14 07:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_category_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hex',
        ),
        migrations.AddField(
            model_name='shoecolor',
            name='hex',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
