# Generated by Django 5.0.1 on 2024-01-18 09:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_shoe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'men'), (2, 'women'), (3, 'kids'), (4, 'featured'), (5, 'Best Sales'), (6, 'sales')], default=4, max_length=4, null=True),
        ),
    ]
