export {default as Logo} from './Logo/Logo'
export {default as Search} from './Search/Search'
export {default as CardInfo} from './CardInfo/CardInfo'
export {default as StaticImg} from './StaticImg/StaticImg'
export {default as Heading} from './Heading/Heading'
export {default as Communicate} from './Communicate/Communicate' 
export {default as InputBox} from './InputBox/InputBox'
export {default as Button} from './Button/Button'
export {AddButton} from './Button/Button'
export {PaymentButton} from './Button/Button'
export {ClearButton} from './Button/Button'
export {default as IncrementDecrementBtn} from './IncrementDecrementBtn/IncrementDecrementBtn'
export {default as CartCard } from './CartCard/CartCard'
export {default as Container} from './Container/Container'
export {ColumnContainer} from './Container/Container'
export {default as Pagination} from './PaginationShoes/Pagination'
